
<a class="navbar-brand" href="{{ app.url }}/">
  <span class="fa fa-hand-peace-o" aria-hidden="true"></span>
  <span class="text">{{ app.name }}</span>
</a>

<button class="navbar-toggler pull-right hidden-sm-up" type="button" data-toggle="collapse" data-target="#sidebar">
  <span class="sr-only">Toggle navigation</span>
  <span class="fa fa-bars" aria-hidden="true"></span>
</button>

{% include "admin-header-navbar.swig" %}
